[2020-09-03 00:15:09,282] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-02T00:00:00+00:00 [queued]>
[2020-09-03 00:15:09,319] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-02T00:00:00+00:00 [queued]>
[2020-09-03 00:15:09,319] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2020-09-03 00:15:09,319] {taskinstance.py:881} INFO - Starting attempt 1 of 2
[2020-09-03 00:15:09,319] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2020-09-03 00:15:09,347] {taskinstance.py:901} INFO - Executing <Task(PythonOperator): populate_transaction_tables> on 2020-09-02T00:00:00+00:00
[2020-09-03 00:15:09,369] {standard_task_runner.py:54} INFO - Started process 31819 to run task
[2020-09-03 00:15:09,554] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'alt_ingestion_pipeline', 'populate_transaction_tables', '2020-09-02T00:00:00+00:00', '--job_id', '12', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/alt_ingestion_pipeline.py', '--cfg_path', '/tmp/tmpu3o8amwl']
[2020-09-03 00:15:09,555] {standard_task_runner.py:78} INFO - Job 12: Subtask populate_transaction_tables
[2020-09-03 00:15:09,640] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: alt_ingestion_pipeline.populate_transaction_tables 2020-09-02T00:00:00+00:00 [running]> MSI.localdomain
[2020-09-03 00:16:19,661] {local_task_job.py:159} WARNING - State of this instance has been externally set to failed. Taking the poison pill.
[2020-09-03 00:16:19,674] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 31819
[2020-09-03 00:16:19,674] {taskinstance.py:955} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-09-03 00:16:19,675] {logging_mixin.py:112} INFO - Some error encountered ... at :  1
[2020-09-03 00:16:19,676] {helpers.py:291} INFO - Process psutil.Process(pid=32396, status='terminated', started='00:16:18') (32396) terminated with exit code None
[2020-09-03 00:16:19,676] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-09-03 00:16:19,706] {taskinstance.py:1070} INFO - Marking task as SUCCESS.dag_id=alt_ingestion_pipeline, task_id=populate_transaction_tables, execution_date=20200902T000000, start_date=20200903T041509, end_date=20200903T041619
[2020-09-03 00:16:19,772] {helpers.py:291} INFO - Process psutil.Process(pid=31819, status='terminated', exitcode=0, started='00:15:09') (31819) terminated with exit code 0
[2020-09-03 00:16:19,773] {local_task_job.py:102} INFO - Task exited with return code 0
